### ISSUE TITLE
Changes needed on the website

### ISSUE THREAD

**Issue by Ankk98** [JIITODC/trident#5]
## Changes needed on the website:

1. [x] Add JODC logo
2. [x] Update Themes/Tracks
3. [x] Update content from Google Doc
4. [x] Replace photos with those of JIIT/JODC
5. [x] Update speakers and judges
6. [x] Add registration Link
7. [x] Update Social Media Links - #4 
8. [x] Add Details of Prizes
9. [x] Link to Code of Conduct
10. [x] Detailed about section with Vision, goals of the event, link to JODC etc. #3 
11. [x] Change meta-data of the website -> it still shows inout hack
12. [x] FAQ: Can I start working on my hack before the event? 
13. [x] FAQ: How Does Judging works? 
14. [x] FAQ: Are there prizes for the girls’ team? 
15. [x] FAQ: Who will own the IP (Intellectual Property) Rights to the product that I have built? 
16. [x] FAQ: Is there any travel reimbursement? 
17. [x] Add: Address of JIIT128 with link to google maps 
18. [x] FAQ: How to reach JIIT128?
19. [x] Change colour combination of white text on light green background with a better one
20. [x] FAQ: Registration fee update - #2 
21. [x] Issue #1 
22. [x]  Add credits in the footer of the website to the original authors
23. [x] Add a readme with a brief info of trident and mention WIP until it is ready.
24. [x] Make gh-pages branch the default one. 
25. [x] Change the registration date to 18 march

**Comment by Ankk98** [comment]
- [ ] Add credits in the footer of the website to the original authors

**Comment by Ankk98** [comment]
Work on the gh-pages branch as it is deployed.
 Also,
- [x] Add a readme with a brief info of trident and mention WIP until it is ready.
- [x] Make gh-pages branch the default one.

**Comment by eldracode** [comment]
I am working on FAQ issues.

**Comment by rexagod** [comment]
> Work on the gh-pages branch as it is deployed.
> Also,
> 
>     * [ ]  Add a readme with a brief info of trident and mention WIP until it is ready.
> 
>     * [ ]  Make gh-pages branch the default one.

Added to issue description above.

**Comment by eldracode** [comment]
@rexagod I did some changes 
https://eldraco19.github.io/trident/

- Fixed FAQ
- Fixed Timeline
- Added map to JIIT128
- Fixed Social links

**Comment by eldracode** [comment]
If this looks fine then I will push it to this repo.

**Comment by karandevtyagi** [comment]
@eldraco19 This looks good.

**Comment by rexagod** [comment]
@karandevtyagi Can you review this? Are all the above ticked issues fixed? Is this good to merge?

**Comment by Ankurk99** [comment]
I have fixed metadata and title of the website.

**Comment by rexagod** [comment]
@Ankurk99 Can you fix this one while you're at it (favicon)? Thanks!

![image](https://user-images.githubusercontent.com/33557095/76684699-1aab7c00-6634-11ea-9013-062436f1821e.png)

**Comment by Ankurk99** [comment]
@rexagod  Done

**Comment by karandevtyagi** [comment]
- [x] Change the registration date to 18 march

**Comment by rexagod** [comment]
>     * [ ]  Change the registration date to 18 march

Added above.

**Comment by Ankurk99** [comment]
I don't think we need this issue anymore, so please close it.

**Comment by rexagod** [comment]
Are all the unticked issues solved? If so, do mark those.

**Comment by rexagod** [comment]
ping @Ankurk99

**Comment by rexagod** [comment]
Remaining sub-issues were made issues.
